// <auto-generated />
using System;
using AIProcessingService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AIProcessingService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AIProcessingDbContext))]
    partial class AIProcessingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AIProcessingService.Domain.Entities.BackgroundPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BackgroundImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("background_image_url");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("FloorColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("floor_color");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PreviewUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("preview_url");

                    b.Property<bool>("RequiresDealerMembership")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_dealer_membership");

                    b.Property<float>("ShadowIntensity")
                        .HasColumnType("real")
                        .HasColumnName("shadow_intensity");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_background_presets_code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_background_presets_is_active");

                    b.ToTable("background_presets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BackgroundImageUrl = "",
                            Code = "white_studio",
                            CreatedAt = new DateTime(2026, 1, 26, 13, 4, 59, 451, DateTimeKind.Utc).AddTicks(6000),
                            Description = "Fondo blanco profesional estilo catálogo",
                            FloorColor = "#FFFFFF",
                            IsActive = true,
                            IsDefault = true,
                            IsPublic = true,
                            Name = "Blanco Infinito",
                            PreviewUrl = "",
                            RequiresDealerMembership = false,
                            ShadowIntensity = 0.3f,
                            SortOrder = 1,
                            ThumbnailUrl = "",
                            Type = "Studio"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BackgroundImageUrl = "",
                            Code = "gray_showroom",
                            CreatedAt = new DateTime(2026, 1, 26, 13, 4, 59, 451, DateTimeKind.Utc).AddTicks(6020),
                            Description = "Fondo de showroom profesional en gris",
                            FloorColor = "#E5E5E5",
                            IsActive = true,
                            IsDefault = false,
                            IsPublic = true,
                            Name = "Showroom Gris",
                            PreviewUrl = "",
                            RequiresDealerMembership = true,
                            ShadowIntensity = 0.4f,
                            SortOrder = 2,
                            ThumbnailUrl = "",
                            Type = "Showroom"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BackgroundImageUrl = "",
                            Code = "dark_studio",
                            CreatedAt = new DateTime(2026, 1, 26, 13, 4, 59, 451, DateTimeKind.Utc).AddTicks(6020),
                            Description = "Fondo oscuro dramático para vehículos de lujo",
                            FloorColor = "#1A1A1A",
                            IsActive = true,
                            IsDefault = false,
                            IsPublic = true,
                            Name = "Estudio Oscuro",
                            PreviewUrl = "",
                            RequiresDealerMembership = true,
                            ShadowIntensity = 0.2f,
                            SortOrder = 3,
                            ThumbnailUrl = "",
                            Type = "Studio"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            BackgroundImageUrl = "",
                            Code = "outdoor_day",
                            CreatedAt = new DateTime(2026, 1, 26, 13, 4, 59, 451, DateTimeKind.Utc).AddTicks(6020),
                            Description = "Escena exterior con cielo azul",
                            FloorColor = "#CCCCCC",
                            IsActive = true,
                            IsDefault = false,
                            IsPublic = true,
                            Name = "Exterior Día",
                            PreviewUrl = "",
                            RequiresDealerMembership = true,
                            ShadowIntensity = 0.5f,
                            SortOrder = 4,
                            ThumbnailUrl = "",
                            Type = "Outdoor"
                        });
                });

            modelBuilder.Entity("AIProcessingService.Domain.Entities.ImageProcessingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("MaskUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("mask_url");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer")
                        .HasColumnName("max_retries");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_version");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("options");

                    b.Property<string>("OriginalImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("original_image_url");

                    b.Property<string>("ProcessedImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("processed_image_url");

                    b.Property<int>("ProcessingTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("processing_time_ms");

                    b.Property<string>("Result")
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<string>("WorkerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("worker_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_image_processing_jobs_created_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_image_processing_jobs_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_image_processing_jobs_user_id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_image_processing_jobs_vehicle_id");

                    b.ToTable("image_processing_jobs", (string)null);
                });

            modelBuilder.Entity("AIProcessingService.Domain.Entities.Spin360Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<int>("FrameCount")
                        .HasColumnType("integer")
                        .HasColumnName("frame_count");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("options");

                    b.Property<int>("ProcessedFrames")
                        .HasColumnType("integer")
                        .HasColumnName("processed_frames");

                    b.Property<int>("ProcessingTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("processing_time_ms");

                    b.Property<string>("Result")
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.Property<string>("SourceImageUrls")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("source_image_urls");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_type");

                    b.Property<string>("SourceVideoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_video_url");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("TotalFrames")
                        .HasColumnType("integer")
                        .HasColumnName("total_frames");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<string>("WorkerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("worker_id");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_spin360_jobs_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_spin360_jobs_user_id");

                    b.HasIndex("VehicleId")
                        .IsUnique()
                        .HasDatabaseName("ix_spin360_jobs_vehicle_id");

                    b.ToTable("spin360_jobs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
