FROM mcr.microsoft.com/dotnet/sdk:8.0

RUN dotnet tool install --global dotnet-watch \
    && export PATH="$PATH:/root/.dotnet/tools" \
    && apt-get update \
    && apt-get install -y curl

WORKDIR /app

COPY RegulatoryAlertService/RegulatoryAlertService.Api/RegulatoryAlertService.Api.csproj ./RegulatoryAlertService/RegulatoryAlertService.Api/
COPY RegulatoryAlertService/RegulatoryAlertService.Application/RegulatoryAlertService.Application.csproj ./RegulatoryAlertService/RegulatoryAlertService.Application/
COPY RegulatoryAlertService/RegulatoryAlertService.Domain/RegulatoryAlertService.Domain.csproj ./RegulatoryAlertService/RegulatoryAlertService.Domain/
COPY RegulatoryAlertService/RegulatoryAlertService.Infrastructure/RegulatoryAlertService.Infrastructure.csproj ./RegulatoryAlertService/RegulatoryAlertService.Infrastructure/

COPY _Shared/CarDealer.Contracts/*.csproj ./_Shared/CarDealer.Contracts/
COPY _Shared/CarDealer.Shared/*.csproj ./_Shared/CarDealer.Shared/

RUN dotnet restore "RegulatoryAlertService/RegulatoryAlertService.Api/RegulatoryAlertService.Api.csproj"

COPY . .

ENV ASPNETCORE_ENVIRONMENT=Development \
    ASPNETCORE_URLS="http://+:80" \
    DOTNET_USE_POLLING_FILE_WATCHER=true

EXPOSE 80

ENTRYPOINT ["dotnet", "watch", "run", "--project", "RegulatoryAlertService/RegulatoryAlertService.Api/RegulatoryAlertService.Api.csproj", "--urls", "http://0.0.0.0:80", "--no-restore"]
