FROM mcr.microsoft.com/dotnet/sdk:8.0 AS base
WORKDIR /src

# Copy all code
COPY . .

# Restore and Build
RUN dotnet restore "CacheService/CacheService.Api/CacheService.Api.csproj"
RUN dotnet build "CacheService/CacheService.Api/CacheService.Api.csproj" -c Release -o /app/build --no-restore

# Set working directory to build output
WORKDIR /app/build

# Expose ports
EXPOSE 80

# Run the compiled dll
ENTRYPOINT ["dotnet", "CacheService.Api.dll"]
