namespace MediaService.Application.DTOs;

/// <summary>
/// Report generated by the image URL health scan job.
/// Contains statistics about image inventory health.
/// </summary>
public class ImageHealthReportDto
{
    /// <summary>
    /// Timestamp when the report was generated (UTC).
    /// </summary>
    public DateTime GeneratedAtUtc { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Total number of images scanned in this run.
    /// </summary>
    public int TotalImagesScanned { get; set; }

    /// <summary>
    /// Number of URLs that returned broken status (403, 404, 410, 500, timeout).
    /// </summary>
    public int BrokenUrlCount { get; set; }

    /// <summary>
    /// Number of URLs that are healthy (200 OK).
    /// </summary>
    public int HealthyUrlCount { get; set; }

    /// <summary>
    /// Percentage of healthy images (0-100).
    /// </summary>
    public double HealthPercentage => TotalImagesScanned > 0
        ? Math.Round((double)HealthyUrlCount / TotalImagesScanned * 100, 2)
        : 100;

    /// <summary>
    /// Top 10 dealers with the most broken images.
    /// </summary>
    public List<DealerBrokenImageSummary> TopDealersWithBrokenImages { get; set; } = new();

    /// <summary>
    /// Breakdown of broken images by HTTP status code.
    /// </summary>
    public Dictionary<int, int> BrokenByStatusCode { get; set; } = new();

    /// <summary>
    /// Duration of the scan in seconds.
    /// </summary>
    public double ScanDurationSeconds { get; set; }

    /// <summary>
    /// Number of images that timed out (>5s).
    /// </summary>
    public int TimeoutCount { get; set; }
}

/// <summary>
/// Summary of broken images for a single dealer.
/// </summary>
public class DealerBrokenImageSummary
{
    public Guid DealerId { get; set; }
    public int BrokenCount { get; set; }
}
