FROM mcr.microsoft.com/dotnet/sdk:8.0 AS base
WORKDIR /src
COPY . .
RUN dotnet restore "TracingService/TracingService.Api/TracingService.Api.csproj"
RUN dotnet build "TracingService/TracingService.Api/TracingService.Api.csproj" -c Release -o /app/build --no-restore
WORKDIR /app/build
EXPOSE 80
ENTRYPOINT ["dotnet", "TracingService.Api.dll"]
