// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StaffService.Infrastructure.Persistence;

#nullable disable

namespace StaffService.Infrastructure.Migrations
{
    [DbContext(typeof(StaffDbContext))]
    partial class StaffDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StaffService.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("HeadId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ParentDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("HeadId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentDepartmentId");

                    b.ToTable("departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            Code = "TECH",
                            CreatedAt = new DateTime(2026, 2, 9, 21, 33, 2, 558, DateTimeKind.Utc).AddTicks(260),
                            CreatedBy = "system",
                            Description = "Engineering and Development",
                            IsActive = true,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            Code = "OPS",
                            CreatedAt = new DateTime(2026, 2, 9, 21, 33, 2, 558, DateTimeKind.Utc).AddTicks(260),
                            CreatedBy = "system",
                            Description = "Business Operations",
                            IsActive = true,
                            Name = "Operations"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            Code = "SUP",
                            CreatedAt = new DateTime(2026, 2, 9, 21, 33, 2, 558, DateTimeKind.Utc).AddTicks(260),
                            CreatedBy = "system",
                            Description = "Customer Service and Support",
                            IsActive = true,
                            Name = "Customer Support"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000004"),
                            Code = "COMP",
                            CreatedAt = new DateTime(2026, 2, 9, 21, 33, 2, 558, DateTimeKind.Utc).AddTicks(260),
                            CreatedBy = "system",
                            Description = "Legal and Regulatory Compliance",
                            IsActive = true,
                            Name = "Compliance"
                        });
                });

            modelBuilder.Entity("StaffService.Domain.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("DefaultRole")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Title");

                    b.ToTable("positions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000001"),
                            Code = "SWE",
                            CreatedAt = new DateTime(2026, 2, 9, 21, 33, 2, 558, DateTimeKind.Utc).AddTicks(260),
                            CreatedBy = "system",
                            DefaultRole = 4,
                            DepartmentId = new Guid("00000000-0000-0000-0001-000000000001"),
                            Description = "Develops and maintains software applications",
                            IsActive = true,
                            Level = 2,
                            Title = "Software Engineer"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000002"),
                            Code = "SS",
                            CreatedAt = new DateTime(2026, 2, 9, 21, 33, 2, 558, DateTimeKind.Utc).AddTicks(260),
                            CreatedBy = "system",
                            DefaultRole = 4,
                            DepartmentId = new Guid("00000000-0000-0000-0001-000000000003"),
                            Description = "Provides customer support",
                            IsActive = true,
                            Level = 1,
                            Title = "Support Specialist"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000003"),
                            Code = "MOD",
                            CreatedAt = new DateTime(2026, 2, 9, 21, 33, 2, 558, DateTimeKind.Utc).AddTicks(260),
                            CreatedBy = "system",
                            DefaultRole = 3,
                            DepartmentId = new Guid("00000000-0000-0000-0001-000000000002"),
                            Description = "Moderates platform content",
                            IsActive = true,
                            Level = 1,
                            Title = "Content Moderator"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000004"),
                            Code = "CO",
                            CreatedAt = new DateTime(2026, 2, 9, 21, 33, 2, 558, DateTimeKind.Utc).AddTicks(260),
                            CreatedBy = "system",
                            DefaultRole = 2,
                            DepartmentId = new Guid("00000000-0000-0000-0001-000000000004"),
                            Description = "Ensures regulatory compliance",
                            IsActive = true,
                            Level = 3,
                            Title = "Compliance Officer"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000005"),
                            Code = "SYSADMIN",
                            CreatedAt = new DateTime(2026, 2, 9, 21, 33, 2, 558, DateTimeKind.Utc).AddTicks(260),
                            CreatedBy = "system",
                            DefaultRole = 1,
                            DepartmentId = new Guid("00000000-0000-0000-0001-000000000001"),
                            Description = "Manages system access and security",
                            IsActive = true,
                            Level = 3,
                            Title = "System Administrator"
                        });
                });

            modelBuilder.Entity("StaffService.Domain.Entities.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InvitationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SupervisorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TerminationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeCode");

                    b.HasIndex("PositionId");

                    b.HasIndex("Role");

                    b.HasIndex("Status");

                    b.HasIndex("SupervisorId");

                    b.ToTable("staff", (string)null);
                });

            modelBuilder.Entity("StaffService.Domain.Entities.StaffInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AssignedRole")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("EmailSentCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InvitedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastEmailSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SupervisorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("InvitedBy");

                    b.HasIndex("PositionId");

                    b.HasIndex("StaffId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("staff_invitations", (string)null);
                });

            modelBuilder.Entity("StaffService.Domain.Entities.StaffPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GrantedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsGranted")
                        .HasColumnType("boolean");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StaffId", "Permission")
                        .IsUnique();

                    b.ToTable("staff_permissions", (string)null);
                });

            modelBuilder.Entity("StaffService.Domain.Entities.Department", b =>
                {
                    b.HasOne("StaffService.Domain.Entities.Staff", "Head")
                        .WithMany()
                        .HasForeignKey("HeadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StaffService.Domain.Entities.Department", "ParentDepartment")
                        .WithMany("ChildDepartments")
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Head");

                    b.Navigation("ParentDepartment");
                });

            modelBuilder.Entity("StaffService.Domain.Entities.Position", b =>
                {
                    b.HasOne("StaffService.Domain.Entities.Department", "Department")
                        .WithMany("Positions")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("StaffService.Domain.Entities.Staff", b =>
                {
                    b.HasOne("StaffService.Domain.Entities.Department", "Department")
                        .WithMany("StaffMembers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StaffService.Domain.Entities.Position", "Position")
                        .WithMany("StaffMembers")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StaffService.Domain.Entities.Staff", "Supervisor")
                        .WithMany("DirectReports")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");

                    b.Navigation("Position");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("StaffService.Domain.Entities.StaffInvitation", b =>
                {
                    b.HasOne("StaffService.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StaffService.Domain.Entities.Staff", "InvitedByStaff")
                        .WithMany()
                        .HasForeignKey("InvitedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StaffService.Domain.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StaffService.Domain.Entities.Staff", "Staff")
                        .WithOne("Invitation")
                        .HasForeignKey("StaffService.Domain.Entities.StaffInvitation", "StaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StaffService.Domain.Entities.Staff", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");

                    b.Navigation("InvitedByStaff");

                    b.Navigation("Position");

                    b.Navigation("Staff");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("StaffService.Domain.Entities.StaffPermission", b =>
                {
                    b.HasOne("StaffService.Domain.Entities.Staff", "Staff")
                        .WithMany("Permissions")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("StaffService.Domain.Entities.Department", b =>
                {
                    b.Navigation("ChildDepartments");

                    b.Navigation("Positions");

                    b.Navigation("StaffMembers");
                });

            modelBuilder.Entity("StaffService.Domain.Entities.Position", b =>
                {
                    b.Navigation("StaffMembers");
                });

            modelBuilder.Entity("StaffService.Domain.Entities.Staff", b =>
                {
                    b.Navigation("DirectReports");

                    b.Navigation("Invitation");

                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
