# =============================================================================
# DOCKER COMPOSE - PRODUCTION/STAGING with Docker Secrets
# =============================================================================
# Usage:
#   docker-compose -f compose.docker.yaml up -d
#
# Prerequisites:
#   1. Copy compose.secrets.example.yaml to compose.secrets.yaml
#   2. Create secret files in ./secrets/ directory
#   3. Set environment variables or use .env file
# =============================================================================

services:
  # ===========================================
  # INFRASTRUCTURE
  # ===========================================
  
  # PostgreSQL - Shared instance for all services
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_MULTIPLE_DATABASES: authservice,userservice,roleservice,errorservice,productservice,notificationservice,billingservice,auditservice,crmservice,mediaservice
    secrets:
      - db_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
    networks:
      - cardealer-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis
  redis:
    image: redis:7-alpine
    container_name: redis
    command: >
      sh -c "redis-server --requirepass $$(cat /run/secrets/redis_password)"
    secrets:
      - redis_password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cardealer-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: cardealer
      RABBITMQ_DEFAULT_PASS_FILE: /run/secrets/rabbitmq_password
    secrets:
      - rabbitmq_password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - cardealer-net
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  # Consul - Service Discovery
  consul:
    image: hashicorp/consul:1.17
    container_name: consul
    ports:
      - "8500:8500"
    volumes:
      - consul_data:/consul/data
    networks:
      - cardealer-net
    command: agent -server -bootstrap-expect=1 -ui -client=0.0.0.0

  # ===========================================
  # API GATEWAY
  # ===========================================
  gateway:
    build:
      context: ./backend
      dockerfile: Gateway/Gateway.Api/Dockerfile
    container_name: gateway
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      JWT_SECRET_KEY_FILE: /run/secrets/jwt_secret_key
      JWT_ISSUER: CarDealer
      JWT_AUDIENCE: CarDealerApp
    secrets:
      - jwt_secret_key
    ports:
      - "8080:80"
    depends_on:
      - consul
    networks:
      - cardealer-net
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ===========================================
  # CORE SERVICES
  # ===========================================
  
  authservice:
    build:
      context: ./backend
      dockerfile: AuthService/AuthService.Api/Dockerfile
    container_name: authservice
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: authservice
      DB_USERNAME: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: cardealer
      CONSUL_ADDRESS: http://consul:8500
    secrets:
      - db_password
      - jwt_secret_key
      - redis_password
      - rabbitmq_password
      - google_client_id
      - google_client_secret
      - microsoft_client_id
      - microsoft_client_secret
    ports:
      - "15085:80"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - cardealer-net
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  userservice:
    build:
      context: ./backend
      dockerfile: UserService/UserService.Api/Dockerfile
    container_name: userservice
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: userservice
      DB_USERNAME: postgres
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: cardealer
      CONSUL_ADDRESS: http://consul:8500
    secrets:
      - db_password
      - jwt_secret_key
      - rabbitmq_password
    ports:
      - "15086:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cardealer-net
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  roleservice:
    build:
      context: ./backend
      dockerfile: RoleService/RoleService.Api/Dockerfile
    container_name: roleservice
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: roleservice
      DB_USERNAME: postgres
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: cardealer
      CONSUL_ADDRESS: http://consul:8500
    secrets:
      - db_password
      - jwt_secret_key
      - rabbitmq_password
    ports:
      - "15087:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cardealer-net
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  errorservice:
    build:
      context: ./backend
      dockerfile: ErrorService/ErrorService.Api/Dockerfile
    container_name: errorservice
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: errorservice
      DB_USERNAME: postgres
      CONSUL_ADDRESS: http://consul:8500
    secrets:
      - db_password
      - jwt_secret_key
    ports:
      - "15083:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cardealer-net
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  productservice:
    build:
      context: ./backend
      dockerfile: ProductService/ProductService.Api/Dockerfile
    container_name: productservice
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: productservice
      DB_USERNAME: postgres
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: cardealer
      CONSUL_ADDRESS: http://consul:8500
    secrets:
      - db_password
      - jwt_secret_key
      - rabbitmq_password
    ports:
      - "15088:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cardealer-net
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  notificationservice:
    build:
      context: ./backend
      dockerfile: NotificationService/NotificationService.Api/Dockerfile
    container_name: notificationservice
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: notificationservice
      DB_USERNAME: postgres
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: cardealer
      CONSUL_ADDRESS: http://consul:8500
      SENDGRID_FROM_EMAIL: noreply@cardealer.com
      SENDGRID_FROM_NAME: CarDealer
      TWILIO_FROM_NUMBER: +1234567890
      FIREBASE_PROJECT_ID: cardealer
    secrets:
      - db_password
      - rabbitmq_password
      - sendgrid_api_key
      - twilio_account_sid
      - twilio_auth_token
      - firebase_service_account
    ports:
      - "15084:80"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - cardealer-net
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ===========================================
  # BUSINESS SERVICES
  # ===========================================
  
  billingservice:
    build:
      context: ./backend
      dockerfile: BillingService/BillingService.Api/Dockerfile
    container_name: billingservice
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: billingservice
      DB_USERNAME: postgres
      CONSUL_ADDRESS: http://consul:8500
    secrets:
      - db_password
      - jwt_secret_key
    ports:
      - "15089:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cardealer-net

  crmservice:
    build:
      context: ./backend
      dockerfile: CRMService/CRMService.Api/Dockerfile
    container_name: crmservice
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: crmservice
      DB_USERNAME: postgres
      CONSUL_ADDRESS: http://consul:8500
    secrets:
      - db_password
      - jwt_secret_key
    ports:
      - "15090:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cardealer-net

  mediaservice:
    build:
      context: ./backend
      dockerfile: MediaService/MediaService.Api/Dockerfile
    container_name: mediaservice
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: mediaservice
      DB_USERNAME: postgres
      CONSUL_ADDRESS: http://consul:8500
    secrets:
      - db_password
      - aws_access_key
      - aws_secret_key
    ports:
      - "15091:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cardealer-net

  auditservice:
    build:
      context: ./backend
      dockerfile: AuditService/AuditService.Api/Dockerfile
    container_name: auditservice
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: auditservice
      DB_USERNAME: postgres
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: cardealer
      CONSUL_ADDRESS: http://consul:8500
    secrets:
      - db_password
      - rabbitmq_password
    ports:
      - "15092:80"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - cardealer-net

  # ===========================================
  # FRONTEND WEB
  # ===========================================
  
  frontend-web:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://gateway:8080
        VITE_APP_NAME: CarDealer
        VITE_APP_VERSION: "1.0.0"
        VITE_BASE_URL: https://cardealer.do
        VITE_SENTRY_DSN: ""
        VITE_GA_TRACKING_ID: ""
        VITE_GOOGLE_MAPS_KEY: ""
        VITE_RECAPTCHA_SITE_KEY: ""
    container_name: frontend-web
    environment:
      # Runtime overrides (optional)
      RUNTIME_API_URL: http://gateway:8080
      RUNTIME_APP_VERSION: "1.0.0"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - gateway
    networks:
      - cardealer-net
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

# ===========================================
# NETWORKS
# ===========================================
networks:
# ===========================================
# NETWORKS
# ===========================================
networks:
  cardealer-net:
    driver: bridge

# ===========================================
# VOLUMES
# ===========================================
volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  consul_data:

# ===========================================
# SECRETS (from files)
# ===========================================
secrets:
  db_password:
    file: ./secrets/db_password.txt
  jwt_secret_key:
    file: ./secrets/jwt_secret_key.txt
  rabbitmq_password:
    file: ./secrets/rabbitmq_password.txt
  redis_password:
    file: ./secrets/redis_password.txt
  sendgrid_api_key:
    file: ./secrets/sendgrid_api_key.txt
  twilio_account_sid:
    file: ./secrets/twilio_account_sid.txt
  twilio_auth_token:
    file: ./secrets/twilio_auth_token.txt
  firebase_service_account:
    file: ./secrets/firebase_service_account.json
  google_client_id:
    file: ./secrets/google_client_id.txt
  google_client_secret:
    file: ./secrets/google_client_secret.txt
  microsoft_client_id:
    file: ./secrets/microsoft_client_id.txt
  microsoft_client_secret:
    file: ./secrets/microsoft_client_secret.txt
  aws_access_key:
    file: ./secrets/aws_access_key.txt
  aws_secret_key:
    file: ./secrets/aws_secret_key.txt
