-- Add missing columns to Users table
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "CreatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "UpdatedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "DealerId" TEXT;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "ExternalAuthProvider" INTEGER;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "ExternalUserId" TEXT;

-- Add missing columns to RefreshTokens table
ALTER TABLE "RefreshTokens" ADD COLUMN IF NOT EXISTS "CreatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
