FROM mcr.microsoft.com/dotnet/sdk:8.0 AS dev
WORKDIR /app

# Copiar archivos de proyecto
COPY DigitalSignatureService/DigitalSignatureService.Domain/*.csproj ./DigitalSignatureService/DigitalSignatureService.Domain/
COPY DigitalSignatureService/DigitalSignatureService.Application/*.csproj ./DigitalSignatureService/DigitalSignatureService.Application/
COPY DigitalSignatureService/DigitalSignatureService.Infrastructure/*.csproj ./DigitalSignatureService/DigitalSignatureService.Infrastructure/
COPY DigitalSignatureService/DigitalSignatureService.Api/*.csproj ./DigitalSignatureService/DigitalSignatureService.Api/

# Restaurar dependencias
RUN dotnet restore ./DigitalSignatureService/DigitalSignatureService.Api/DigitalSignatureService.Api.csproj

# Copiar código fuente
COPY DigitalSignatureService/ ./DigitalSignatureService/

WORKDIR /app/DigitalSignatureService/DigitalSignatureService.Api
EXPOSE 80
ENV ASPNETCORE_URLS=http://+:80

ENTRYPOINT ["dotnet", "watch", "run", "--no-launch-profile"]
