FROM mcr.microsoft.com/dotnet/sdk:8.0 AS base
WORKDIR /src

# Copy all code
COPY . .

# Restore dependencies
RUN dotnet restore "ContactService/ContactService.Api/ContactService.Api.csproj"

# Set working directory to Api project
WORKDIR /src/ContactService/ContactService.Api

# Expose ports
EXPOSE 80 4022

# Run with dotnet watch for hot reload
ENTRYPOINT ["dotnet", "watch", "run", "--no-launch-profile", "--urls", "http://+:80"]
