FROM mcr.microsoft.com/dotnet/sdk:8.0 AS base
WORKDIR /src

# Copy all code
COPY . .

# Restore dependencies
RUN dotnet restore "BillingService/BillingService.Api/BillingService.Api.csproj"

# Set working directory to Api project
WORKDIR /src/BillingService/BillingService.Api

# Expose ports
EXPOSE 80 4022

# Sin watch para evitar crashes en Docker
ENTRYPOINT ["dotnet", "run", "--no-launch-profile", "--urls", "http://+:80"]
