FROM mcr.microsoft.com/dotnet/sdk:8.0 AS dev
WORKDIR /app

# Copiar archivos de proyecto
COPY TaxComplianceService/TaxComplianceService.Domain/*.csproj ./TaxComplianceService/TaxComplianceService.Domain/
COPY TaxComplianceService/TaxComplianceService.Application/*.csproj ./TaxComplianceService/TaxComplianceService.Application/
COPY TaxComplianceService/TaxComplianceService.Infrastructure/*.csproj ./TaxComplianceService/TaxComplianceService.Infrastructure/
COPY TaxComplianceService/TaxComplianceService.Api/*.csproj ./TaxComplianceService/TaxComplianceService.Api/

# Restaurar dependencias
RUN dotnet restore ./TaxComplianceService/TaxComplianceService.Api/TaxComplianceService.Api.csproj

# Copiar código fuente
COPY TaxComplianceService/ ./TaxComplianceService/

WORKDIR /app/TaxComplianceService/TaxComplianceService.Api
EXPOSE 80
ENV ASPNETCORE_URLS=http://+:80

ENTRYPOINT ["dotnet", "watch", "run", "--no-launch-profile"]
