FROM mcr.microsoft.com/dotnet/sdk:8.0

RUN dotnet tool install --global dotnet-watch \
    && export PATH="$PATH:/root/.dotnet/tools" \
    && apt-get update \
    && apt-get install -y curl

WORKDIR /app

COPY FeatureStoreService/FeatureStoreService.Api/FeatureStoreService.Api.csproj ./FeatureStoreService/FeatureStoreService.Api/
COPY FeatureStoreService/FeatureStoreService.Application/FeatureStoreService.Application.csproj ./FeatureStoreService/FeatureStoreService.Application/
COPY FeatureStoreService/FeatureStoreService.Domain/FeatureStoreService.Domain.csproj ./FeatureStoreService/FeatureStoreService.Domain/
COPY FeatureStoreService/FeatureStoreService.Infrastructure/FeatureStoreService.Infrastructure.csproj ./FeatureStoreService/FeatureStoreService.Infrastructure/

COPY _Shared/CarDealer.Contracts/*.csproj ./_Shared/CarDealer.Contracts/
COPY _Shared/CarDealer.Shared/*.csproj ./_Shared/CarDealer.Shared/

RUN dotnet restore "FeatureStoreService/FeatureStoreService.Api/FeatureStoreService.Api.csproj"

COPY . .

ENV ASPNETCORE_ENVIRONMENT=Development \
    ASPNETCORE_URLS="http://+:80" \
    DOTNET_USE_POLLING_FILE_WATCHER=true

EXPOSE 80

ENTRYPOINT ["dotnet", "watch", "run", "--project", "FeatureStoreService/FeatureStoreService.Api/FeatureStoreService.Api.csproj", "--urls", "http://0.0.0.0:80", "--no-restore"]
