FROM mcr.microsoft.com/dotnet/sdk:8.0 AS dev
WORKDIR /app

# Copiar archivos de proyecto
COPY VehicleRegistryService/VehicleRegistryService.Domain/*.csproj ./VehicleRegistryService/VehicleRegistryService.Domain/
COPY VehicleRegistryService/VehicleRegistryService.Application/*.csproj ./VehicleRegistryService/VehicleRegistryService.Application/
COPY VehicleRegistryService/VehicleRegistryService.Infrastructure/*.csproj ./VehicleRegistryService/VehicleRegistryService.Infrastructure/
COPY VehicleRegistryService/VehicleRegistryService.Api/*.csproj ./VehicleRegistryService/VehicleRegistryService.Api/

# Restaurar dependencias
RUN dotnet restore ./VehicleRegistryService/VehicleRegistryService.Api/VehicleRegistryService.Api.csproj

# Copiar código fuente
COPY VehicleRegistryService/ ./VehicleRegistryService/

WORKDIR /app/VehicleRegistryService/VehicleRegistryService.Api
EXPOSE 80
ENV ASPNETCORE_URLS=http://+:80

ENTRYPOINT ["dotnet", "watch", "run", "--no-launch-profile"]
