// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RateLimitingService.Infrastructure.Data;

#nullable disable

namespace RateLimitingService.Infrastructure.Migrations
{
    [DbContext(typeof(RateLimitDbContext))]
    [Migration("20251203024011_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "hstore");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RateLimitingService.Core.Models.RateLimitViolation", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AllowedLimit")
                        .HasColumnType("integer")
                        .HasColumnName("allowed_limit");

                    b.Property<int>("AttemptedRequests")
                        .HasColumnType("integer")
                        .HasColumnName("attempted_requests");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("endpoint");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("identifier");

                    b.Property<string>("IdentifierType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("identifier_type");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<Dictionary<string, string>>("Metadata")
                        .IsRequired()
                        .HasColumnType("hstore");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rule_id");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("rule_name");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<DateTime>("ViolatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("violated_at");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .HasDatabaseName("idx_violations_identifier");

                    b.HasIndex("IdentifierType")
                        .HasDatabaseName("idx_violations_identifier_type");

                    b.HasIndex("ViolatedAt")
                        .HasDatabaseName("idx_violations_violated_at");

                    b.HasIndex("Identifier", "ViolatedAt")
                        .HasDatabaseName("idx_violations_identifier_date");

                    b.HasIndex("IdentifierType", "ViolatedAt")
                        .HasDatabaseName("idx_violations_type_date");

                    b.ToTable("rate_limit_violations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
