FROM mcr.microsoft.com/dotnet/sdk:8.0 AS base
WORKDIR /src

COPY . .

RUN dotnet restore "BackupDRService/BackupDRService.Api/BackupDRService.Api.csproj"

WORKDIR /src/BackupDRService/BackupDRService.Api

EXPOSE 80

ENTRYPOINT ["dotnet", "run", "--no-launch-profile", "--urls", "http://+:80"]
