FROM mcr.microsoft.com/dotnet/sdk:8.0 AS base
WORKDIR /src

# Copy all code
COPY . .

# Restore dependencies
RUN dotnet restore "InvoicingService/InvoicingService.Api/InvoicingService.Api.csproj"

# Set working directory to Api project
WORKDIR /src/InvoicingService/InvoicingService.Api

# Expose ports
EXPOSE 80 4022

# Run with dotnet run (dotnet watch causes issues in containers)
ENTRYPOINT ["dotnet", "run", "--no-launch-profile", "--urls", "http://+:80"]
