FROM mcr.microsoft.com/dotnet/sdk:8.0 AS development
WORKDIR /src

# Copiar archivos de proyecto
COPY DataPipelineService.Domain/*.csproj ./DataPipelineService.Domain/
COPY DataPipelineService.Application/*.csproj ./DataPipelineService.Application/
COPY DataPipelineService.Infrastructure/*.csproj ./DataPipelineService.Infrastructure/
COPY DataPipelineService.Api/*.csproj ./DataPipelineService.Api/

# Restaurar dependencias
RUN dotnet restore DataPipelineService.Api/DataPipelineService.Api.csproj

# Copiar código fuente
COPY . .

WORKDIR /src/DataPipelineService.Api

EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080
ENV ASPNETCORE_ENVIRONMENT=Development

# Hot reload
ENTRYPOINT ["dotnet", "watch", "run", "--no-launch-profile"]
