// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReviewService.Infrastructure.Persistence;

#nullable disable

namespace ReviewService.Infrastructure.Migrations
{
    [DbContext(typeof(ReviewDbContext))]
    [Migration("20260109193605_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reviewservice")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReviewService.Domain.Entities.FraudDetectionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CheckType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("check_type");

                    b.Property<DateTime>("CheckedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("checked_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ConfidenceScore")
                        .HasColumnType("integer")
                        .HasColumnName("confidence_score");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("details");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("result");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CheckType")
                        .HasDatabaseName("ix_fraud_detection_logs_check_type");

                    b.HasIndex("CheckedAt")
                        .HasDatabaseName("ix_fraud_detection_logs_checked_at");

                    b.HasIndex("ConfidenceScore")
                        .HasDatabaseName("ix_fraud_detection_logs_confidence_score");

                    b.HasIndex("Result")
                        .HasDatabaseName("ix_fraud_detection_logs_result");

                    b.HasIndex("ReviewId")
                        .HasDatabaseName("ix_fraud_detection_logs_review_id");

                    b.HasIndex("CheckType", "Result")
                        .HasDatabaseName("ix_fraud_detection_logs_type_result");

                    b.ToTable("fraud_detection_logs", "reviewservice");
                });

            modelBuilder.Entity("ReviewService.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AutoRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<string>("BuyerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BuyerPhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FlagReason")
                        .HasColumnType("text");

                    b.Property<int>("HelpfulVotes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerifiedPurchase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModeratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModeratedById")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasAnnotation("MaxValue", 5)
                        .HasAnnotation("MinValue", 1);

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TotalVotes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TrustScore")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<string>("UserIpAddress")
                        .HasColumnType("text");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WasAutoRequested")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId")
                        .HasDatabaseName("IX_reviews_buyer_id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("IX_reviews_order_id")
                        .HasFilter("\"OrderId\" IS NOT NULL");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("IX_reviews_seller_id");

                    b.HasIndex("IsApproved", "Rating")
                        .HasDatabaseName("IX_reviews_approved_rating");

                    b.HasIndex("BuyerId", "SellerId", "VehicleId")
                        .IsUnique()
                        .HasDatabaseName("IX_reviews_unique_buyer_seller_vehicle")
                        .HasFilter("\"VehicleId\" IS NOT NULL");

                    b.ToTable("reviews", "reviewservice");
                });

            modelBuilder.Entity("ReviewService.Domain.Entities.ReviewHelpfulVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsHelpful")
                        .HasColumnType("boolean")
                        .HasColumnName("is_helpful");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("user_ip_address");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("voted_at");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId")
                        .HasDatabaseName("ix_review_helpful_votes_review_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_review_helpful_votes_user_id");

                    b.HasIndex("UserIpAddress")
                        .HasDatabaseName("ix_review_helpful_votes_ip_address");

                    b.HasIndex("VotedAt")
                        .HasDatabaseName("ix_review_helpful_votes_voted_at");

                    b.HasIndex("ReviewId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_review_helpful_votes_review_user");

                    b.ToTable("review_helpful_votes", "reviewservice");
                });

            modelBuilder.Entity("ReviewService.Domain.Entities.ReviewRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BuyerEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("buyer_email");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id");

                    b.Property<string>("BuyerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("buyer_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("LastReminderAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_reminder_sent");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RemindersSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reminders_sent");

                    b.Property<DateTime>("RequestSentAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("requested_at");

                    b.Property<DateTime?>("ReviewCreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<Guid?>("ReviewId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("request_token");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("BuyerEmail")
                        .HasDatabaseName("ix_review_requests_buyer_email");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_review_requests_expires_at");

                    b.HasIndex("RequestSentAt")
                        .HasDatabaseName("ix_review_requests_requested_at");

                    b.HasIndex("ReviewId");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_review_requests_status");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_review_requests_token");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("ix_review_requests_status_expires");

                    b.HasIndex("SellerId", "BuyerId", "VehicleId")
                        .HasDatabaseName("ix_review_requests_seller_buyer_vehicle");

                    b.ToTable("review_requests", "reviewservice");
                });

            modelBuilder.Entity("ReviewService.Domain.Entities.ReviewResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId")
                        .IsUnique()
                        .HasDatabaseName("IX_review_responses_review_id");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("IX_review_responses_seller_id");

                    b.ToTable("review_responses", "reviewservice");
                });

            modelBuilder.Entity("ReviewService.Domain.Entities.ReviewSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AverageRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FiveStarReviews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("FourStarReviews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("LastReviewDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OneStarReviews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal>("PositivePercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<int>("ThreeStarReviews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalReviews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TwoStarReviews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VerifiedPurchaseReviews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("AverageRating")
                        .HasDatabaseName("IX_review_summaries_average_rating");

                    b.HasIndex("SellerId")
                        .IsUnique()
                        .HasDatabaseName("IX_review_summaries_seller_id");

                    b.HasIndex("TotalReviews")
                        .HasDatabaseName("IX_review_summaries_total_reviews");

                    b.ToTable("review_summaries", "reviewservice");
                });

            modelBuilder.Entity("ReviewService.Domain.Entities.SellerBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BadgeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("badge_type");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Criteria")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("granted_at");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("QualifyingStats")
                        .HasColumnType("jsonb")
                        .HasColumnName("qualifying_stats");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("BadgeType")
                        .HasDatabaseName("ix_seller_badges_badge_type");

                    b.HasIndex("GrantedAt")
                        .HasDatabaseName("ix_seller_badges_granted_at");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_seller_badges_is_active");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("ix_seller_badges_seller_id");

                    b.HasIndex("SellerId", "BadgeType", "IsActive")
                        .HasDatabaseName("ix_seller_badges_seller_type_active");

                    b.ToTable("seller_badges", "reviewservice");
                });

            modelBuilder.Entity("ReviewService.Domain.Entities.FraudDetectionLog", b =>
                {
                    b.HasOne("ReviewService.Domain.Entities.Review", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("ReviewService.Domain.Entities.ReviewHelpfulVote", b =>
                {
                    b.HasOne("ReviewService.Domain.Entities.Review", "Review")
                        .WithMany("HelpfulVotesList")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("ReviewService.Domain.Entities.ReviewRequest", b =>
                {
                    b.HasOne("ReviewService.Domain.Entities.Review", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewId");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("ReviewService.Domain.Entities.ReviewResponse", b =>
                {
                    b.HasOne("ReviewService.Domain.Entities.Review", "Review")
                        .WithOne("Response")
                        .HasForeignKey("ReviewService.Domain.Entities.ReviewResponse", "ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("ReviewService.Domain.Entities.Review", b =>
                {
                    b.Navigation("HelpfulVotesList");

                    b.Navigation("Response");
                });
#pragma warning restore 612, 618
        }
    }
}
