FROM mcr.microsoft.com/dotnet/sdk:8.0

RUN dotnet tool install --global dotnet-watch \
    && export PATH="$PATH:/root/.dotnet/tools" \
    && apt-get update \
    && apt-get install -y curl

WORKDIR /app

COPY SpyneIntegrationService/SpyneIntegrationService.Api/SpyneIntegrationService.Api.csproj ./SpyneIntegrationService/SpyneIntegrationService.Api/
COPY SpyneIntegrationService/SpyneIntegrationService.Application/SpyneIntegrationService.Application.csproj ./SpyneIntegrationService/SpyneIntegrationService.Application/
COPY SpyneIntegrationService/SpyneIntegrationService.Domain/SpyneIntegrationService.Domain.csproj ./SpyneIntegrationService/SpyneIntegrationService.Domain/
COPY SpyneIntegrationService/SpyneIntegrationService.Infrastructure/SpyneIntegrationService.Infrastructure.csproj ./SpyneIntegrationService/SpyneIntegrationService.Infrastructure/

COPY _Shared/CarDealer.Contracts/*.csproj ./_Shared/CarDealer.Contracts/
COPY _Shared/CarDealer.Shared/*.csproj ./_Shared/CarDealer.Shared/

RUN dotnet restore "SpyneIntegrationService/SpyneIntegrationService.Api/SpyneIntegrationService.Api.csproj"

COPY . .

ENV ASPNETCORE_ENVIRONMENT=Development \
    ASPNETCORE_URLS="http://+:80" \
    DOTNET_USE_POLLING_FILE_WATCHER=true

EXPOSE 80

ENTRYPOINT ["dotnet", "watch", "run", "--project", "SpyneIntegrationService/SpyneIntegrationService.Api/SpyneIntegrationService.Api.csproj", "--urls", "http://0.0.0.0:80", "--no-restore"]
