// <auto-generated />
using System;
using AdvertisingService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdvertisingService.Infrastructure.Migrations
{
    [DbContext(typeof(AdvertisingDbContext))]
    partial class AdvertisingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdvertisingService.Domain.Entities.AdCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BillingReferenceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Clicks")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FixedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("PlacementType")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PricePerView")
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("PricingModel")
                        .HasColumnType("integer");

                    b.Property<decimal>("QualityScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(0.50m);

                    b.Property<decimal>("SpentBudget")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TotalViewsPurchased")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.Property<int>("ViewsConsumed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("idx_ad_campaigns_vehicle");

                    b.HasIndex("OwnerId", "OwnerType")
                        .HasDatabaseName("idx_ad_campaigns_owner");

                    b.HasIndex("PlacementType", "Status")
                        .HasDatabaseName("idx_ad_campaigns_placement_status");

                    b.ToTable("ad_campaigns", (string)null);
                });

            modelBuilder.Entity("AdvertisingService.Domain.Entities.AdClick", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ImpressionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "RecordedAt")
                        .HasDatabaseName("idx_ad_clicks_campaign");

                    b.ToTable("ad_clicks", (string)null);
                });

            modelBuilder.Entity("AdvertisingService.Domain.Entities.AdImpression", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<string>("IpHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Section")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "RecordedAt")
                        .HasDatabaseName("idx_ad_impressions_campaign");

                    b.ToTable("ad_impressions", (string)null);
                });

            modelBuilder.Entity("AdvertisingService.Domain.Entities.BrandConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BrandKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoInitials")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("VehicleCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrandKey")
                        .IsUnique();

                    b.ToTable("brand_configs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000001"),
                            BrandKey = "toyota",
                            DisplayName = "Toyota",
                            DisplayOrder = 1,
                            IsVisible = true,
                            LogoInitials = "TO",
                            Route = "/buscar?marca=toyota",
                            UpdatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleCount = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000002"),
                            BrandKey = "honda",
                            DisplayName = "Honda",
                            DisplayOrder = 2,
                            IsVisible = true,
                            LogoInitials = "HO",
                            Route = "/buscar?marca=honda",
                            UpdatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleCount = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000003"),
                            BrandKey = "hyundai",
                            DisplayName = "Hyundai",
                            DisplayOrder = 3,
                            IsVisible = true,
                            LogoInitials = "HY",
                            Route = "/buscar?marca=hyundai",
                            UpdatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleCount = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000004"),
                            BrandKey = "kia",
                            DisplayName = "Kia",
                            DisplayOrder = 4,
                            IsVisible = true,
                            LogoInitials = "KI",
                            Route = "/buscar?marca=kia",
                            UpdatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleCount = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000005"),
                            BrandKey = "nissan",
                            DisplayName = "Nissan",
                            DisplayOrder = 5,
                            IsVisible = true,
                            LogoInitials = "NI",
                            Route = "/buscar?marca=nissan",
                            UpdatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleCount = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000006"),
                            BrandKey = "mazda",
                            DisplayName = "Mazda",
                            DisplayOrder = 6,
                            IsVisible = true,
                            LogoInitials = "MA",
                            Route = "/buscar?marca=mazda",
                            UpdatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleCount = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000007"),
                            BrandKey = "ford",
                            DisplayName = "Ford",
                            DisplayOrder = 7,
                            IsVisible = true,
                            LogoInitials = "FO",
                            Route = "/buscar?marca=ford",
                            UpdatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleCount = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000008"),
                            BrandKey = "chevrolet",
                            DisplayName = "Chevrolet",
                            DisplayOrder = 8,
                            IsVisible = true,
                            LogoInitials = "CH",
                            Route = "/buscar?marca=chevrolet",
                            UpdatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleCount = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000009"),
                            BrandKey = "bmw",
                            DisplayName = "BMW",
                            DisplayOrder = 9,
                            IsVisible = true,
                            LogoInitials = "BM",
                            Route = "/buscar?marca=bmw",
                            UpdatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleCount = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-00000000000a"),
                            BrandKey = "mercedes-benz",
                            DisplayName = "Mercedes-Benz",
                            DisplayOrder = 10,
                            IsVisible = true,
                            LogoInitials = "ME",
                            Route = "/buscar?marca=mercedes-benz",
                            UpdatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleCount = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-00000000000b"),
                            BrandKey = "audi",
                            DisplayName = "Audi",
                            DisplayOrder = 11,
                            IsVisible = true,
                            LogoInitials = "AU",
                            Route = "/buscar?marca=audi",
                            UpdatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleCount = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-00000000000c"),
                            BrandKey = "volkswagen",
                            DisplayName = "Volkswagen",
                            DisplayOrder = 12,
                            IsVisible = true,
                            LogoInitials = "VO",
                            Route = "/buscar?marca=volkswagen",
                            UpdatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleCount = 0
                        });
                });

            modelBuilder.Entity("AdvertisingService.Domain.Entities.CategoryImageConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Gradient")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("from-blue-600 to-blue-800");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsTrending")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("VehicleCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryKey")
                        .IsUnique();

                    b.ToTable("category_image_configs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000001"),
                            CategoryKey = "suv",
                            Description = "Versatilidad y espacio para toda la familia",
                            DisplayName = "SUV",
                            DisplayOrder = 1,
                            Gradient = "from-blue-600 to-blue-800",
                            ImageUrl = "",
                            IsTrending = true,
                            IsVisible = true,
                            Route = "/buscar?tipo=suv",
                            UpdatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleCount = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000002"),
                            CategoryKey = "sedan",
                            Description = "Elegancia y eficiencia para el día a día",
                            DisplayName = "Sedán",
                            DisplayOrder = 2,
                            Gradient = "from-primary to-primary/90",
                            ImageUrl = "",
                            IsTrending = false,
                            IsVisible = true,
                            Route = "/buscar?tipo=sedan",
                            UpdatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleCount = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000003"),
                            CategoryKey = "camioneta",
                            Description = "Potencia y capacidad de carga",
                            DisplayName = "Camioneta",
                            DisplayOrder = 3,
                            Gradient = "from-amber-600 to-amber-800",
                            ImageUrl = "",
                            IsTrending = false,
                            IsVisible = true,
                            Route = "/buscar?tipo=camioneta",
                            UpdatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleCount = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000004"),
                            CategoryKey = "deportivo",
                            Description = "Rendimiento y adrenalina pura",
                            DisplayName = "Deportivo",
                            DisplayOrder = 4,
                            Gradient = "from-red-600 to-red-800",
                            ImageUrl = "",
                            IsTrending = false,
                            IsVisible = true,
                            Route = "/buscar?tipo=deportivo",
                            UpdatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleCount = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000005"),
                            CategoryKey = "electrico",
                            Description = "El futuro de la movilidad sostenible",
                            DisplayName = "Eléctrico",
                            DisplayOrder = 5,
                            Gradient = "from-green-600 to-green-800",
                            ImageUrl = "",
                            IsTrending = true,
                            IsVisible = true,
                            Route = "/buscar?tipo=electrico",
                            UpdatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleCount = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000006"),
                            CategoryKey = "hibrido",
                            Description = "Lo mejor de dos mundos",
                            DisplayName = "Híbrido",
                            DisplayOrder = 6,
                            Gradient = "from-teal-600 to-teal-800",
                            ImageUrl = "",
                            IsTrending = false,
                            IsVisible = true,
                            Route = "/buscar?tipo=hibrido",
                            UpdatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleCount = 0
                        });
                });

            modelBuilder.Entity("AdvertisingService.Domain.Entities.RotationConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AlgorithmType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxVehiclesShown")
                        .HasColumnType("integer");

                    b.Property<int>("RefreshIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("Section")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("WeightCtr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(0.25m);

                    b.Property<decimal>("WeightQualityScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(0.25m);

                    b.Property<decimal>("WeightRecency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(0.20m);

                    b.Property<decimal>("WeightRemainingBudget")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(0.30m);

                    b.HasKey("Id");

                    b.HasIndex("Section")
                        .IsUnique();

                    b.ToTable("rotation_configs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            AlgorithmType = 0,
                            CreatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MaxVehiclesShown = 8,
                            RefreshIntervalMinutes = 30,
                            Section = 0,
                            UpdatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            WeightCtr = 0.25m,
                            WeightQualityScore = 0.25m,
                            WeightRecency = 0.20m,
                            WeightRemainingBudget = 0.30m
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            AlgorithmType = 3,
                            CreatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MaxVehiclesShown = 4,
                            RefreshIntervalMinutes = 60,
                            Section = 1,
                            UpdatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            WeightCtr = 0.20m,
                            WeightQualityScore = 0.20m,
                            WeightRecency = 0.20m,
                            WeightRemainingBudget = 0.40m
                        });
                });

            modelBuilder.Entity("AdvertisingService.Domain.Entities.AdClick", b =>
                {
                    b.HasOne("AdvertisingService.Domain.Entities.AdCampaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("AdvertisingService.Domain.Entities.AdImpression", b =>
                {
                    b.HasOne("AdvertisingService.Domain.Entities.AdCampaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");
                });
#pragma warning restore 612, 618
        }
    }
}
