// <auto-generated />
using System;
using KYCService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KYCService.Infrastructure.Migrations
{
    [DbContext(typeof(KYCDbContext))]
    [Migration("20260209120000_AddSectorToKYCProfile")]
    partial class AddSectorToKYCProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // This migration adds the Sector column to kyc_profiles table
            // The full model is defined in KYCDbContextModelSnapshot.cs
#pragma warning restore 612, 618
        }
    }
}
