FROM mcr.microsoft.com/dotnet/sdk:8.0

RUN dotnet tool install --global dotnet-watch \
    && export PATH="$PATH:/root/.dotnet/tools" \
    && apt-get update \
    && apt-get install -y curl

WORKDIR /app

COPY ReportingService/ReportingService.Api/ReportingService.Api.csproj ./ReportingService/ReportingService.Api/
COPY ReportingService/ReportingService.Application/ReportingService.Application.csproj ./ReportingService/ReportingService.Application/
COPY ReportingService/ReportingService.Domain/ReportingService.Domain.csproj ./ReportingService/ReportingService.Domain/
COPY ReportingService/ReportingService.Infrastructure/ReportingService.Infrastructure.csproj ./ReportingService/ReportingService.Infrastructure/

COPY _Shared/CarDealer.Contracts/*.csproj ./_Shared/CarDealer.Contracts/
COPY _Shared/CarDealer.Shared/*.csproj ./_Shared/CarDealer.Shared/

RUN dotnet restore "ReportingService/ReportingService.Api/ReportingService.Api.csproj"

COPY . .

ENV ASPNETCORE_ENVIRONMENT=Development \
    ASPNETCORE_URLS="http://+:80" \
    DOTNET_USE_POLLING_FILE_WATCHER=true

EXPOSE 80

ENTRYPOINT ["dotnet", "watch", "run", "--project", "ReportingService/ReportingService.Api/ReportingService.Api.csproj", "--urls", "http://0.0.0.0:80", "--no-restore"]
