#!/usr/bin/env pwsh
# ===========================================================================
# Update-ComposeSecrets.ps1 - Actualizar compose.secrets.yaml desde archivos
# ===========================================================================
# Este script lee todos los archivos en secrets/ y actualiza compose.secrets.yaml
# automáticamente. Útil para Sprint 1 después de configurar servicios externos.
# ===========================================================================

Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "UPDATE COMPOSE SECRETS" -ForegroundColor Cyan
Write-Host "========================================`n" -ForegroundColor Cyan

$secretsDir = "./secrets"
$composeFile = "./compose.secrets.yaml"

# Verificar que exista el directorio secrets/
if (-not (Test-Path $secretsDir)) {
    Write-Host "❌ ERROR: Directory $secretsDir not found" -ForegroundColor Red
    Write-Host "   Create it first: mkdir secrets" -ForegroundColor Yellow
    exit 1
}

# Leer todos los archivos de secrets
$secretFiles = Get-ChildItem -Path $secretsDir -File | Where-Object { $_.Extension -in @('.txt', '.json', '.pem', '.key') }

if ($secretFiles.Count -eq 0) {
    Write-Host "⚠️  WARNING: No secret files found in $secretsDir" -ForegroundColor Yellow
    Write-Host "   Add your secrets there first (see SPRINT_1_CHECKLIST.md)" -ForegroundColor Yellow
    exit 0
}

Write-Host "📁 Found $($secretFiles.Count) secret files:`n" -ForegroundColor Green

$secrets = @{}

foreach ($file in $secretFiles) {
    $content = Get-Content -Path $file.FullName -Raw
    $content = $content.Trim()
    
    if ($content.Length -eq 0) {
        Write-Host "   ⚠️  $($file.Name) - EMPTY" -ForegroundColor Yellow
        continue
    }
    
    # Detectar si es placeholder común
    $isPlaceholder = $content -match "^(your|placeholder|REPLACE|example|TODO|XXX)" -or 
                     $content -match "^<.*>$" -or
                     $content -eq "changeme"
    
    if ($isPlaceholder) {
        Write-Host "   ⚠️  $($file.Name) - PLACEHOLDER" -ForegroundColor Yellow
        continue
    }
    
    # Mapear nombre de archivo a variable de entorno
    $envVarName = switch ($file.BaseName) {
        "jwt_secret_key" { "JWT__KEY" }
        "db_password" { "POSTGRES_PASSWORD" }
        "google_maps_api_key" { "GOOGLE_MAPS_API_KEY" }
        "google_oauth_client_id" { "GOOGLE_OAUTH_CLIENT_ID" }
        "google_oauth_client_secret" { "GOOGLE_OAUTH_CLIENT_SECRET" }
        "firebase_service_account" { "FIREBASE_SERVICE_ACCOUNT_JSON" }
        "stripe_publishable_key" { "STRIPE_PUBLISHABLE_KEY" }
        "stripe_secret_key" { "STRIPE_SECRET_KEY" }
        "stripe_webhook_secret" { "STRIPE_WEBHOOK_SECRET" }
        "sendgrid_api_key" { "SENDGRID_API_KEY" }
        "resend_api_key" { "RESEND_API_KEY" }
        "twilio_account_sid" { "TWILIO_ACCOUNT_SID" }
        "twilio_auth_token" { "TWILIO_AUTH_TOKEN" }
        "twilio_phone_number" { "TWILIO_PHONE_NUMBER" }
        "aws_access_key_id" { "AWS_ACCESS_KEY_ID" }
        "aws_secret_access_key" { "AWS_SECRET_ACCESS_KEY" }
        "aws_s3_bucket" { "AWS_S3_BUCKET" }
        "aws_region" { "AWS_REGION" }
        "sentry_dsn_backend" { "SENTRY_DSN_BACKEND" }
        "sentry_dsn_frontend" { "SENTRY_DSN_FRONTEND" }
        default { $file.BaseName.ToUpper().Replace("-", "_") }
    }
    
    $secrets[$envVarName] = $content
    
    # Preview del valor (primeros 20 chars)
    $preview = if ($content.Length -gt 20) { $content.Substring(0, 20) + "..." } else { $content }
    Write-Host "   ✅ $envVarName = $preview" -ForegroundColor Green
}

Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "GENERATING compose.secrets.yaml" -ForegroundColor Cyan
Write-Host "========================================`n" -ForegroundColor Cyan

# Crear backup del archivo existente
if (Test-Path $composeFile) {
    $backupFile = "$composeFile.backup-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
    Copy-Item $composeFile $backupFile
    Write-Host "📦 Backup created: $backupFile" -ForegroundColor Cyan
}

# Generar nuevo compose.secrets.yaml
$yaml = @"
# ============================================================================
# compose.secrets.yaml - Secrets Configuration
# ============================================================================
# GENERATED BY: Update-ComposeSecrets.ps1
# DATE: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
# 
# USAGE:
#   docker-compose -f compose.yaml -f compose.secrets.yaml up -d
# 
# ⚠️  DO NOT COMMIT THIS FILE TO GIT! ⚠️
# ============================================================================

version: '3.8'

services:
"@

# AuthService
if ($secrets.ContainsKey("JWT__KEY")) {
    $yaml += @"

  authservice:
    environment:
      - Jwt__Key=$($secrets["JWT__KEY"])
"@
    if ($secrets.ContainsKey("GOOGLE_OAUTH_CLIENT_ID")) {
        $yaml += @"

      - Authentication__Google__ClientId=$($secrets["GOOGLE_OAUTH_CLIENT_ID"])
      - Authentication__Google__ClientSecret=$($secrets["GOOGLE_OAUTH_CLIENT_SECRET"])
"@
    }
}

# BillingService
if ($secrets.ContainsKey("STRIPE_SECRET_KEY")) {
    $yaml += @"

  billingservice:
    environment:
      - Stripe__SecretKey=$($secrets["STRIPE_SECRET_KEY"])
      - Stripe__PublishableKey=$($secrets["STRIPE_PUBLISHABLE_KEY"])
"@
    if ($secrets.ContainsKey("STRIPE_WEBHOOK_SECRET")) {
        $yaml += @"

      - Stripe__WebhookSecret=$($secrets["STRIPE_WEBHOOK_SECRET"])
"@
    }
}

# NotificationService
if ($secrets.ContainsKey("SENDGRID_API_KEY") -or $secrets.ContainsKey("RESEND_API_KEY")) {
    $yaml += @"

  notificationservice:
    environment:
"@
    if ($secrets.ContainsKey("SENDGRID_API_KEY")) {
        $yaml += @"

      - NotificationSettings__SendGrid__ApiKey=$($secrets["SENDGRID_API_KEY"])
"@
    }
    if ($secrets.ContainsKey("RESEND_API_KEY")) {
        $yaml += @"

      - NotificationSettings__Resend__ApiKey=$($secrets["RESEND_API_KEY"])
"@
    }
    if ($secrets.ContainsKey("TWILIO_ACCOUNT_SID")) {
        $yaml += @"

      - NotificationSettings__Twilio__AccountSid=$($secrets["TWILIO_ACCOUNT_SID"])
      - NotificationSettings__Twilio__AuthToken=$($secrets["TWILIO_AUTH_TOKEN"])
      - NotificationSettings__Twilio__PhoneNumber=$($secrets["TWILIO_PHONE_NUMBER"])
"@
    }
    if ($secrets.ContainsKey("FIREBASE_SERVICE_ACCOUNT_JSON")) {
        $yaml += @"

      - Firebase__ServiceAccountJson=$($secrets["FIREBASE_SERVICE_ACCOUNT_JSON"])
"@
    }
}

# MediaService
if ($secrets.ContainsKey("AWS_ACCESS_KEY_ID")) {
    $yaml += @"

  mediaservice:
    environment:
      - S3Storage__AccessKey=$($secrets["AWS_ACCESS_KEY_ID"])
      - S3Storage__SecretKey=$($secrets["AWS_SECRET_ACCESS_KEY"])
      - S3Storage__BucketName=$($secrets["AWS_S3_BUCKET"])
      - S3Storage__Region=$($secrets["AWS_REGION"])
"@
}

# Frontend
if ($secrets.ContainsKey("GOOGLE_MAPS_API_KEY")) {
    $yaml += @"

  frontend-web:
    environment:
      - VITE_GOOGLE_MAPS_API_KEY=$($secrets["GOOGLE_MAPS_API_KEY"])
      - VITE_STRIPE_PUBLISHABLE_KEY=$($secrets["STRIPE_PUBLISHABLE_KEY"])
"@
    if ($secrets.ContainsKey("SENTRY_DSN_FRONTEND")) {
        $yaml += @"

      - VITE_SENTRY_DSN=$($secrets["SENTRY_DSN_FRONTEND"])
"@
    }
}

# PostgreSQL databases
if ($secrets.ContainsKey("POSTGRES_PASSWORD")) {
    $dbServices = @(
        "authservice-db", "userservice-db", "roleservice-db", "productservice-db",
        "mediaservice-db", "notificationservice-db", "billingservice-db", "crmservice-db",
        "errorservice-db", "auditservice-db", "adminservice-db", "reportsservice-db",
        "schedulerservice-db", "searchservice-db", "contactservice-db", "appointmentservice-db",
        "realestateservice-db", "invoicingservice-db", "financeservice-db", "marketingservice-db"
    )
    
    foreach ($db in $dbServices) {
        $yaml += @"

  $db:
    environment:
      - POSTGRES_PASSWORD=$($secrets["POSTGRES_PASSWORD"])
"@
    }
}

# Escribir archivo
$yaml | Out-File -FilePath $composeFile -Encoding utf8 -Force

Write-Host "✅ $composeFile updated successfully!" -ForegroundColor Green
Write-Host "`n📋 Summary:" -ForegroundColor Cyan
Write-Host "   - Secrets loaded: $($secrets.Count)" -ForegroundColor White
Write-Host "   - File size: $((Get-Item $composeFile).Length) bytes" -ForegroundColor White

Write-Host "`n🚀 Next steps:" -ForegroundColor Yellow
Write-Host "   1. Review the file: cat $composeFile" -ForegroundColor White
Write-Host "   2. Test services: docker-compose -f compose.yaml -f $composeFile config" -ForegroundColor White
Write-Host "   3. Start services: docker-compose -f compose.yaml -f $composeFile up -d" -ForegroundColor White

Write-Host "`n✅ Done!`n" -ForegroundColor Green
