FROM mcr.microsoft.com/dotnet/sdk:8.0 AS dev
WORKDIR /app

# Copiar archivos de proyecto
COPY AntiMoneyLaunderingService/AntiMoneyLaunderingService.Domain/*.csproj ./AntiMoneyLaunderingService/AntiMoneyLaunderingService.Domain/
COPY AntiMoneyLaunderingService/AntiMoneyLaunderingService.Application/*.csproj ./AntiMoneyLaunderingService/AntiMoneyLaunderingService.Application/
COPY AntiMoneyLaunderingService/AntiMoneyLaunderingService.Infrastructure/*.csproj ./AntiMoneyLaunderingService/AntiMoneyLaunderingService.Infrastructure/
COPY AntiMoneyLaunderingService/AntiMoneyLaunderingService.Api/*.csproj ./AntiMoneyLaunderingService/AntiMoneyLaunderingService.Api/

# Restaurar dependencias
RUN dotnet restore ./AntiMoneyLaunderingService/AntiMoneyLaunderingService.Api/AntiMoneyLaunderingService.Api.csproj

# Copiar código fuente
COPY AntiMoneyLaunderingService/ ./AntiMoneyLaunderingService/

WORKDIR /app/AntiMoneyLaunderingService/AntiMoneyLaunderingService.Api
EXPOSE 80
ENV ASPNETCORE_URLS=http://+:80

ENTRYPOINT ["dotnet", "watch", "run", "--no-launch-profile"]
