include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    # Deshabilitado temporalmente para reducir warnings de estilo
    # - always_put_required_named_parameters_first
    - annotate_overrides
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    # Deshabilitado para widgetbook
    # - avoid_relative_lib_imports
    - avoid_return_types_on_setters
    - avoid_shadowing_type_parameters
    - avoid_types_as_parameter_names
    - camel_case_extensions
    - curly_braces_in_flow_control_structures
    - empty_catches
    - empty_constructor_bodies
    - library_names
    - library_prefixes
    - no_duplicate_case_values
    - null_closures
    # Deshabilitado temporalmente
    # - omit_local_variable_types
    - prefer_adjacent_string_concatenation
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_contains
    - prefer_final_fields
    - prefer_for_elements_to_map_fromIterable
    - prefer_generic_function_type_aliases
    - prefer_if_null_operators
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - prefer_single_quotes
    - prefer_spread_collections
    - recursive_getters
    - slash_for_doc_comments
    - type_init_formals
    # Deshabilitado temporalmente
    # - unawaited_futures
    - unnecessary_const
    - unnecessary_new
    - unnecessary_null_in_if_null_operators
    - unnecessary_this
    - unrelated_type_equality_checks
    - use_function_type_syntax_for_parameters
    - use_rethrow_when_possible
    - valid_regexps

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "widgetbook/**"
    - "**/generated/**"
  errors:
    # Convertir warnings de estilo a info para reducir ruido
    prefer_const_constructors: info
    prefer_const_literals_to_create_immutables: info
    prefer_const_declarations: info
    deprecated_member_use: warning
    use_super_parameters: info
    avoid_print: warning
    unused_local_variable: warning
    unused_field: warning
    dead_code: warning
    invalid_annotation_target: ignore
