FROM mcr.microsoft.com/dotnet/sdk:8.0 AS base
WORKDIR /src

# Copy all code
COPY . .

# Restore dependencies
RUN dotnet restore "SchedulerService/SchedulerService.Api/SchedulerService.Api.csproj"

# Set working directory to Api project
WORKDIR /src/SchedulerService/SchedulerService.Api

# Expose ports
EXPOSE 80

# Run with dotnet run (not watch - more stable)
ENTRYPOINT ["dotnet", "run", "--no-launch-profile", "--urls", "http://+:80"]
