FROM mcr.microsoft.com/dotnet/sdk:8.0

RUN dotnet tool install --global dotnet-watch \
    && export PATH="$PATH:/root/.dotnet/tools" \
    && apt-get update \
    && apt-get install -y curl

WORKDIR /app

COPY ComplianceIntegrationService/ComplianceIntegrationService.Api/ComplianceIntegrationService.Api.csproj ./ComplianceIntegrationService/ComplianceIntegrationService.Api/
COPY ComplianceIntegrationService/ComplianceIntegrationService.Application/ComplianceIntegrationService.Application.csproj ./ComplianceIntegrationService/ComplianceIntegrationService.Application/
COPY ComplianceIntegrationService/ComplianceIntegrationService.Domain/ComplianceIntegrationService.Domain.csproj ./ComplianceIntegrationService/ComplianceIntegrationService.Domain/
COPY ComplianceIntegrationService/ComplianceIntegrationService.Infrastructure/ComplianceIntegrationService.Infrastructure.csproj ./ComplianceIntegrationService/ComplianceIntegrationService.Infrastructure/

COPY _Shared/CarDealer.Contracts/*.csproj ./_Shared/CarDealer.Contracts/
COPY _Shared/CarDealer.Shared/*.csproj ./_Shared/CarDealer.Shared/

RUN dotnet restore "ComplianceIntegrationService/ComplianceIntegrationService.Api/ComplianceIntegrationService.Api.csproj"

COPY . .

ENV ASPNETCORE_ENVIRONMENT=Development \
    ASPNETCORE_URLS="http://+:80" \
    DOTNET_USE_POLLING_FILE_WATCHER=true

EXPOSE 80

ENTRYPOINT ["dotnet", "watch", "run", "--project", "ComplianceIntegrationService/ComplianceIntegrationService.Api/ComplianceIntegrationService.Api.csproj", "--urls", "http://0.0.0.0:80", "--no-restore"]
