// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VehiclesSaleService.Infrastructure.Persistence;

#nullable disable

namespace VehiclesSaleService.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VehiclesSaleService.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomFieldsSchemaJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ParentId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 5, 21, 13, 19, 880, DateTimeKind.Utc).AddTicks(7057),
                            CustomFieldsSchemaJson = "[\r\n                    {\"key\":\"make\",\"label\":\"Marca\",\"type\":\"string\",\"required\":true},\r\n                    {\"key\":\"model\",\"label\":\"Modelo\",\"type\":\"string\",\"required\":true},\r\n                    {\"key\":\"year\",\"label\":\"Año\",\"type\":\"number\",\"required\":true},\r\n                    {\"key\":\"mileage\",\"label\":\"Kilometraje\",\"type\":\"number\",\"unit\":\"km\"},\r\n                    {\"key\":\"transmission\",\"label\":\"Transmisión\",\"type\":\"string\"},\r\n                    {\"key\":\"fuelType\",\"label\":\"Combustible\",\"type\":\"string\"},\r\n                    {\"key\":\"color\",\"label\":\"Color\",\"type\":\"string\"}\r\n                ]",
                            Description = "Autos, motos y vehículos comerciales",
                            IsActive = true,
                            Level = 0,
                            Name = "Vehículos",
                            Slug = "vehiculos",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 12, 5, 21, 13, 19, 880, DateTimeKind.Utc).AddTicks(7062),
                            CustomFieldsSchemaJson = "[\r\n                    {\"key\":\"bedrooms\",\"label\":\"Habitaciones\",\"type\":\"number\",\"required\":true},\r\n                    {\"key\":\"bathrooms\",\"label\":\"Baños\",\"type\":\"number\",\"required\":true},\r\n                    {\"key\":\"sqft\",\"label\":\"Área\",\"type\":\"number\",\"unit\":\"m²\"},\r\n                    {\"key\":\"parking\",\"label\":\"Estacionamiento\",\"type\":\"boolean\"},\r\n                    {\"key\":\"furnished\",\"label\":\"Amueblado\",\"type\":\"boolean\"}\r\n                ]",
                            Description = "Casas, departamentos y terrenos",
                            IsActive = true,
                            Level = 0,
                            Name = "Inmuebles",
                            Slug = "inmuebles",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 12, 5, 21, 13, 19, 880, DateTimeKind.Utc).AddTicks(7065),
                            CustomFieldsSchemaJson = "[\r\n                    {\"key\":\"brand\",\"label\":\"Marca\",\"type\":\"string\",\"required\":true},\r\n                    {\"key\":\"condition\",\"label\":\"Condición\",\"type\":\"string\"},\r\n                    {\"key\":\"warranty\",\"label\":\"Garantía\",\"type\":\"boolean\"}\r\n                ]",
                            Description = "Computadoras, celulares y gadgets",
                            IsActive = true,
                            Level = 0,
                            Name = "Electrónicos",
                            Slug = "electronicos",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("VehiclesSaleService.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("USD");

                    b.Property<string>("CustomFieldsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Name");

                    b.HasIndex("Price");

                    b.HasIndex("SellerId");

                    b.HasIndex("Status");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("VehiclesSaleService.Domain.Entities.ProductCustomField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("string");

                    b.Property<bool>("IsSearchable")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("IsSearchable");

                    b.HasIndex("Key");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId", "Key");

                    b.ToTable("product_custom_fields", (string)null);
                });

            modelBuilder.Entity("VehiclesSaleService.Domain.Entities.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId", "SortOrder");

                    b.ToTable("product_images", (string)null);
                });

            modelBuilder.Entity("VehiclesSaleService.Domain.Entities.Category", b =>
                {
                    b.HasOne("VehiclesSaleService.Domain.Entities.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("VehiclesSaleService.Domain.Entities.Product", b =>
                {
                    b.HasOne("VehiclesSaleService.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("VehiclesSaleService.Domain.Entities.ProductCustomField", b =>
                {
                    b.HasOne("VehiclesSaleService.Domain.Entities.Product", "Product")
                        .WithMany("CustomFields")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("VehiclesSaleService.Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("VehiclesSaleService.Domain.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("VehiclesSaleService.Domain.Entities.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("VehiclesSaleService.Domain.Entities.Product", b =>
                {
                    b.Navigation("CustomFields");

                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
