// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VehiclesSaleService.Infrastructure.Persistence;

#nullable disable

namespace VehiclesSaleService.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VehiclesSaleService.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("DealerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DealerId")
                        .HasDatabaseName("IX_Category_DealerId");

                    b.HasIndex("IsActive");

                    b.HasIndex("Level");

                    b.HasIndex("ParentId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DealerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Sedans, coupes, hatchbacks and sports cars",
                            IsActive = true,
                            IsSystem = false,
                            Level = 0,
                            Name = "Cars",
                            Slug = "cars",
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2026, 1, 3, 21, 31, 35, 843, DateTimeKind.Utc).AddTicks(9120)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DealerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Pickup trucks and commercial trucks",
                            IsActive = true,
                            IsSystem = false,
                            Level = 0,
                            Name = "Trucks",
                            Slug = "trucks",
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2026, 1, 3, 21, 31, 35, 843, DateTimeKind.Utc).AddTicks(9120)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DealerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Sport utility vehicles and crossovers",
                            IsActive = true,
                            IsSystem = false,
                            Level = 0,
                            Name = "SUVs & Crossovers",
                            Slug = "suvs-crossovers",
                            SortOrder = 3,
                            UpdatedAt = new DateTime(2026, 1, 3, 21, 31, 35, 843, DateTimeKind.Utc).AddTicks(9120)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DealerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Sport bikes, cruisers and ATVs",
                            IsActive = true,
                            IsSystem = false,
                            Level = 0,
                            Name = "Motorcycles",
                            Slug = "motorcycles",
                            SortOrder = 4,
                            UpdatedAt = new DateTime(2026, 1, 3, 21, 31, 35, 843, DateTimeKind.Utc).AddTicks(9130)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DealerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Boats, jet skis and watercraft",
                            IsActive = true,
                            IsSystem = false,
                            Level = 0,
                            Name = "Boats & Watercraft",
                            Slug = "boats-watercraft",
                            SortOrder = 5,
                            UpdatedAt = new DateTime(2026, 1, 3, 21, 31, 35, 843, DateTimeKind.Utc).AddTicks(9130)
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DealerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Recreational vehicles and campers",
                            IsActive = true,
                            IsSystem = false,
                            Level = 0,
                            Name = "RVs & Campers",
                            Slug = "rvs-campers",
                            SortOrder = 6,
                            UpdatedAt = new DateTime(2026, 1, 3, 21, 31, 35, 843, DateTimeKind.Utc).AddTicks(9130)
                        });
                });

            modelBuilder.Entity("VehiclesSaleService.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AccidentHistory")
                        .HasColumnType("boolean");

                    b.Property<string>("BodyStyle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CarfaxReportUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("CertificationProgram")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Country")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("USA");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("USD");

                    b.Property<int?>("Cylinders")
                        .HasColumnType("integer");

                    b.Property<Guid>("DealerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<int>("Doors")
                        .HasColumnType("integer");

                    b.Property<string>("DriveType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EngineSize")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ExteriorColor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("FavoriteCount")
                        .HasColumnType("integer");

                    b.Property<string>("FeaturesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Generation")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("HasCleanTitle")
                        .HasColumnType("boolean");

                    b.Property<int?>("Horsepower")
                        .HasColumnType("integer");

                    b.Property<int>("InquiryCount")
                        .HasColumnType("integer");

                    b.Property<string>("InteriorColor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("InteriorMaterial")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsCertified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastServiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("MakeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer");

                    b.Property<string>("MileageUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MpgCity")
                        .HasColumnType("integer");

                    b.Property<int?>("MpgCombined")
                        .HasColumnType("integer");

                    b.Property<int?>("MpgHighway")
                        .HasColumnType("integer");

                    b.Property<string>("PackagesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]");

                    b.Property<int?>("PreviousOwners")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Seats")
                        .HasColumnType("integer");

                    b.Property<string>("SellerCity")
                        .HasColumnType("text");

                    b.Property<string>("SellerEmail")
                        .HasColumnType("text");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("SellerLogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SellerPhone")
                        .HasColumnType("text");

                    b.Property<decimal?>("SellerRating")
                        .HasColumnType("numeric");

                    b.Property<int?>("SellerReviewCount")
                        .HasColumnType("integer");

                    b.Property<string>("SellerState")
                        .HasColumnType("text");

                    b.Property<int>("SellerType")
                        .HasColumnType("integer");

                    b.Property<bool>("SellerVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("SellerWhatsApp")
                        .HasColumnType("text");

                    b.Property<string>("ServiceHistoryNotes")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime?>("SoldAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StockNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("Torque")
                        .HasColumnType("integer");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Trim")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("VIN")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.Property<string>("WarrantyInfo")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("BodyStyle");

                    b.HasIndex("CategoryId");

                    b.HasIndex("City");

                    b.HasIndex("Condition");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DealerId")
                        .HasDatabaseName("IX_Vehicle_DealerId");

                    b.HasIndex("FuelType");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("IsFeatured");

                    b.HasIndex("Make");

                    b.HasIndex("MakeId");

                    b.HasIndex("Mileage");

                    b.HasIndex("Model");

                    b.HasIndex("ModelId");

                    b.HasIndex("Price");

                    b.HasIndex("SellerId");

                    b.HasIndex("State");

                    b.HasIndex("Status");

                    b.HasIndex("Transmission");

                    b.HasIndex("VIN")
                        .IsUnique();

                    b.HasIndex("VehicleType");

                    b.HasIndex("Year");

                    b.HasIndex("ZipCode");

                    b.HasIndex("State", "City");

                    b.HasIndex("Status", "IsDeleted");

                    b.HasIndex("Make", "Model", "Year");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("VehiclesSaleService.Domain.Entities.VehicleImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Caption")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("DealerId")
                        .HasColumnType("uuid");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("ImageType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("MimeType")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DealerId")
                        .HasDatabaseName("IX_VehicleImage_DealerId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("VehicleId", "IsPrimary");

                    b.HasIndex("VehicleId", "SortOrder");

                    b.ToTable("vehicle_images", (string)null);
                });

            modelBuilder.Entity("VehiclesSaleService.Domain.Entities.VehicleMake", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SortOrder");

                    b.ToTable("vehicle_makes", (string)null);
                });

            modelBuilder.Entity("VehiclesSaleService.Domain.Entities.VehicleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultBodyStyle")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MakeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("StartYear")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("MakeId");

                    b.HasIndex("Name");

                    b.HasIndex("MakeId", "Name")
                        .IsUnique();

                    b.ToTable("vehicle_models", (string)null);
                });

            modelBuilder.Entity("VehiclesSaleService.Domain.Entities.VehicleTrim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("BaseMSRP")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DriveType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EngineSize")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FuelType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("Horsepower")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MpgCity")
                        .HasColumnType("integer");

                    b.Property<int?>("MpgCombined")
                        .HasColumnType("integer");

                    b.Property<int?>("MpgHighway")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Torque")
                        .HasColumnType("integer");

                    b.Property<string>("Transmission")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ModelId");

                    b.HasIndex("Year");

                    b.HasIndex("ModelId", "Year", "Name")
                        .IsUnique();

                    b.ToTable("vehicle_trims", (string)null);
                });

            modelBuilder.Entity("VehiclesSaleService.Domain.Entities.Category", b =>
                {
                    b.HasOne("VehiclesSaleService.Domain.Entities.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("VehiclesSaleService.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("VehiclesSaleService.Domain.Entities.Category", "Category")
                        .WithMany("Vehicles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("VehiclesSaleService.Domain.Entities.VehicleImage", b =>
                {
                    b.HasOne("VehiclesSaleService.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Images")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehiclesSaleService.Domain.Entities.VehicleModel", b =>
                {
                    b.HasOne("VehiclesSaleService.Domain.Entities.VehicleMake", "Make")
                        .WithMany("Models")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Make");
                });

            modelBuilder.Entity("VehiclesSaleService.Domain.Entities.VehicleTrim", b =>
                {
                    b.HasOne("VehiclesSaleService.Domain.Entities.VehicleModel", "Model")
                        .WithMany("Trims")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("VehiclesSaleService.Domain.Entities.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("VehiclesSaleService.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("VehiclesSaleService.Domain.Entities.VehicleMake", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("VehiclesSaleService.Domain.Entities.VehicleModel", b =>
                {
                    b.Navigation("Trims");
                });
#pragma warning restore 612, 618
        }
    }
}
