FROM mcr.microsoft.com/dotnet/sdk:8.0 AS base
WORKDIR /src
COPY . .
RUN dotnet restore "IdempotencyService/IdempotencyService.Api/IdempotencyService.Api.csproj"
RUN dotnet build "IdempotencyService/IdempotencyService.Api/IdempotencyService.Api.csproj" -c Release -o /app/build --no-restore
WORKDIR /app/build
EXPOSE 80
ENTRYPOINT ["dotnet", "IdempotencyService.Api.dll"]
