FROM mcr.microsoft.com/dotnet/sdk:8.0 AS base
WORKDIR /src

# Copy all source code
COPY . .

# Restore dependencies
RUN dotnet restore "HealthCheckService/HealthCheckService.Api/HealthCheckService.Api.csproj"

# Build the project in Release mode
RUN dotnet build "HealthCheckService/HealthCheckService.Api/HealthCheckService.Api.csproj" -c Release -o /app/build --no-restore

# Set working directory to output folder
WORKDIR /app/build

# Expose port 80
EXPOSE 80

# Run the precompiled DLL directly
ENTRYPOINT ["dotnet", "HealthCheckService.Api.dll"]
