FROM mcr.microsoft.com/dotnet/sdk:8.0 AS dev
WORKDIR /app

# Copiar archivos de proyecto
COPY ConsumerProtectionService/ConsumerProtectionService.Domain/*.csproj ./ConsumerProtectionService/ConsumerProtectionService.Domain/
COPY ConsumerProtectionService/ConsumerProtectionService.Application/*.csproj ./ConsumerProtectionService/ConsumerProtectionService.Application/
COPY ConsumerProtectionService/ConsumerProtectionService.Infrastructure/*.csproj ./ConsumerProtectionService/ConsumerProtectionService.Infrastructure/
COPY ConsumerProtectionService/ConsumerProtectionService.Api/*.csproj ./ConsumerProtectionService/ConsumerProtectionService.Api/

# Restaurar dependencias
RUN dotnet restore ./ConsumerProtectionService/ConsumerProtectionService.Api/ConsumerProtectionService.Api.csproj

# Copiar código fuente
COPY ConsumerProtectionService/ ./ConsumerProtectionService/

WORKDIR /app/ConsumerProtectionService/ConsumerProtectionService.Api
EXPOSE 80
ENV ASPNETCORE_URLS=http://+:80

ENTRYPOINT ["dotnet", "watch", "run", "--no-launch-profile"]
