// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SearchAgent.Infrastructure.Persistence;

#nullable disable

namespace SearchAgent.Infrastructure.Migrations
{
    [DbContext(typeof(SearchAgentDbContext))]
    partial class SearchAgentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SearchAgent.Domain.Entities.SearchAgentConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AiSearchTrafficPercent")
                        .HasColumnType("integer");

                    b.Property<int>("CacheTtlSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EnableCache")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxQueriesPerMinutePerIp")
                        .HasColumnType("integer");

                    b.Property<int>("MaxRelaxationLevel")
                        .HasColumnType("integer");

                    b.Property<int>("MaxResultsPerPage")
                        .HasColumnType("integer");

                    b.Property<float>("MaxSponsoredPercentage")
                        .HasColumnType("real");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("integer");

                    b.Property<int>("MinResultsPerPage")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PriceRelaxPercent")
                        .HasColumnType("integer");

                    b.Property<float>("SemanticCacheThreshold")
                        .HasColumnType("real");

                    b.Property<float>("SponsoredAffinityThreshold")
                        .HasColumnType("real");

                    b.Property<string>("SponsoredLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SponsoredPositions")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SystemPromptOverride")
                        .HasColumnType("text");

                    b.Property<float>("Temperature")
                        .HasColumnType("real");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("YearRelaxRange")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("search_agent_config", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            AiSearchTrafficPercent = 100,
                            CacheTtlSeconds = 3600,
                            CreatedAt = new DateTime(2026, 3, 2, 20, 50, 45, 541, DateTimeKind.Utc).AddTicks(2440),
                            EnableCache = true,
                            IsEnabled = true,
                            MaxQueriesPerMinutePerIp = 60,
                            MaxRelaxationLevel = 5,
                            MaxResultsPerPage = 40,
                            MaxSponsoredPercentage = 0.25f,
                            MaxTokens = 1024,
                            MinResultsPerPage = 8,
                            Model = "claude-haiku-4-5-20251001",
                            PriceRelaxPercent = 25,
                            SemanticCacheThreshold = 0.95f,
                            SponsoredAffinityThreshold = 0.45f,
                            SponsoredLabel = "Patrocinado",
                            SponsoredPositions = "1,5,10",
                            Temperature = 0.2f,
                            UpdatedAt = new DateTime(2026, 3, 2, 20, 50, 45, 541, DateTimeKind.Utc).AddTicks(2440),
                            YearRelaxRange = 2
                        });
                });

            modelBuilder.Entity("SearchAgent.Domain.Entities.SearchQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("Confidence")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FilterLevel")
                        .HasColumnType("integer");

                    b.Property<string>("FiltersJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer");

                    b.Property<int>("OrganicResultCount")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalQuery")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ReformulatedQuery")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SponsoredResultCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalResultCount")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("WasCached")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("search_queries", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
